[package]
name = "add_binary"
version = "0.1.0"
authors = ["eruca <nickwill1984@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
